springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

  endpoint.health:
    show-details: never

  tracing:
    sampling:
      probability: 0.1
